version: "3.4"

services:
  gooutsafe:
    image: gooutsafe:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
  redis:
    image: "redis:6.0.8-alpine"
