version: "3.4"

services:
  gooutsafe:
    image: gooutsafe:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - elastic-search
      - database
      - redis
    ports:
      - 5000:5000
    environment:
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - DATABASE_URI
      - ELASTICSEARCH_URL
      - SECRET_KEY
      - WTF_CSRF
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_SERVER
      - FLASK_PROFILER_ADMIN
      - FLASK_PROFILER_PASSWORD
  database:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
  elastic-search:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.0"
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
  redis:
    image: "redis:6.0.8-alpine"
    ports:
      - 6379:6379

volumes:
  db-data:
