version: "3.4"

 

services:
  gooutsafe:
    image: gooutsafe:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
  redis:
    image: "redis:6.0.8-alpine"
    ports:
      - 6379:6379